
version: '3.0'

services:
    engine:
        build:
            context: .
        volumes:
            - .:/usr/src/app:rw
        command: tail -F Dockerfile
        ports:
            - 8080:8080
        environment:
            - MEMCACHESTATS_HOST=192.168.1.20
            - MEMCACHESTATS_PORT=11211
